# Generated by pip2nix 0.7.0
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Babel" = super.buildPythonPackage {
    name = "Babel-2.3.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/96/ba2a2462ed25ca0e651fb7b66e7080f5315f91425a07ea5b34d7c870c114/Babel-2.3.4.tar.gz";
      sha256 = "0x98qqqw35xllpcama013a9788ly84z8dm1w2wwfpxh2710c8df5";
    };
  };
  "Beaker" = super.buildPythonPackage {
    name = "Beaker-1.5.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/f9/7d699c3397357fa8634ec4b3d1510d07d69fd68b74478bd5b32814f56715/Beaker-1.5.4.tar.gz";
      sha256 = "0svi19az0wz4m6v70jrvxs2dc75jlmg07fn1q9gwi44l1spccgd1";
    };
  };
  "Django" = super.buildPythonPackage {
    name = "Django-1.11.13";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/e3/b9226c6a12bd5984daa68d41f066df0021a511bfbc86b83cdfc7dce956d9/Django-1.11.13.tar.gz";
      sha256 = "19d4c1rlbhmbvbxvskvqjb2aw4dnf2cqi1hhdh11ykdy1a7gxba6";
    };
  };
  "GeoIP" = super.buildPythonPackage {
    name = "GeoIP-1.3.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/7b/a463b7c3df8ef4b9c92906da29ddc9e464d4045f00c475ad31cdb9a97aae/GeoIP-1.3.2.tar.gz";
      sha256 = "1rphxf3vrn8wywjgr397f49s0s22m83lpwcq45lm0h2p45mdm458";
    };
  };
  "Jinja2" = super.buildPythonPackage {
    name = "Jinja2-2.9.6";
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/61/f820ff0076a2599dd39406dcb858ecb239438c02ce706c8e91131ab9c7f1/Jinja2-2.9.6.tar.gz";
      sha256 = "1zzrkywhziqffrzks14kzixz7nd4yh2vc0fb04a68vfd2ai03anx";
    };
  };
  "Markdown" = super.buildPythonPackage {
    name = "Markdown-2.6.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/82/dfe242bcfd9eec0e7bf93a80a8f8d8515a95b980c44f5c0b45606397a423/Markdown-2.6.9.tar.gz";
      sha256 = "10dgdzha9vym7wi5p3lbk2fw1rahw9q65zmnm6rnhmxr71r7kbvk";
    };
  };
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-0.23";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz";
      sha256 = "1hvip33wva3fnmvfp9x5klqri7hpl1hkgqmjbss18nmrb7zimv54";
    };
  };
  "Paste" = super.buildPythonPackage {
    name = "Paste-2.0.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/c3/5c2f7c7a02e4f58d4454353fa1c32c94f79fa4e36d07a67c0ac295ea369e/Paste-2.0.3.tar.gz";
      sha256 = "062jk0nlxf6lb2wwj6zc20rlvrwsnikpkh90y0dn8cjch93s6ii3";
    };
  };
  "Pillow" = super.buildPythonPackage {
    name = "Pillow-4.3.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."olefile"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/82/ec499c78bfe4ecaa91c2f3000040451d187ed0a816d58b8543e29c48827f/Pillow-4.3.0.tar.gz";
      sha256 = "09xmn7rl6840sli2iz1k3fgxfgmri2nqz6vkinmb9mgg8ifp2z59";
    };
  };
  "PyJWT" = super.buildPythonPackage {
    name = "PyJWT-1.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/af/7f500e3e587c927c88422099ce7ed9247f89f3217cabf00d3f48fe3ad5fe/PyJWT-1.6.1.tar.gz";
      sha256 = "0fp6m8ymvcb3khl03iam1639gi4skzi78f37x051mgz3dxwabjys";
    };
  };
  "PyNaCl" = super.buildPythonPackage {
    name = "PyNaCl-1.1.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."cffi"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/f3/02605b056e465bf162508c4d1635a2bccd9abd1ee3ed2a1bb4e9676eac33/PyNaCl-1.1.2.tar.gz";
      sha256 = "135gz0020fqx8fbr9izpwyq49aww202nkqacq0cw61xz99sjpx9j";
    };
  };
  "PySocks" = super.buildPythonPackage {
    name = "PySocks-1.6.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/38/edca891ce16827a1de45cc347e4b6c22311eba25838b9825a5e6c48cf560/PySocks-1.6.7.tar.gz";
      sha256 = "1krkiss578zqwcg4c8iqz1hwscwhsvy2djp3xyvps5gsgvr2j0yh";
    };
  };
  "PyYAML" = super.buildPythonPackage {
    name = "PyYAML-3.12";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz";
      sha256 = "1aqjl8dk9amd4zr99n8v2qxzgmr2hdvqfma4zh7a41rj6336c9sr";
    };
  };
  "Pygments" = super.buildPythonPackage {
    name = "Pygments-2.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz";
      sha256 = "1k78qdvir1yb1c634nkv6rbga8wv4289xarghmsbbvzhvr311bnv";
    };
  };
  "SOAPpy" = super.buildPythonPackage {
    name = "SOAPpy-0.12.22";
    doCheck = false;
    propagatedBuildInputs = [
      self."wstools"
      self."defusedxml"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/1b/29cbe26b2b98804d65e934925ced9810883bdda9eacba3f993ad60bfe271/SOAPpy-0.12.22.zip";
      sha256 = "19a7nj76vv01nkbka672z0gl713dsqs4bpx8wr5189dndf84a277";
    };
  };
  "adal" = super.buildPythonPackage {
    name = "adal-0.4.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."PyJWT"
      self."requests"
      self."python-dateutil"
      self."cryptography"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/55/fe57a0c94680f7b72bb524c085d28a0e407dcaa695ab927d1a904fdc7b6a/adal-0.4.5.tar.gz";
      sha256 = "0lz2bxsmnc9fidkshlnbbccrykq9kzwj5vpwxqfswwp27x3zvpf5";
    };
  };
  "ansible" = super.buildPythonPackage {
    name = "ansible-2.5.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."Jinja2"
      self."PyYAML"
      self."paramiko"
      self."cryptography"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/5f/3e7d8243159ba831942b851891d8eeac04615323a91e8447365aa7311299/ansible-2.5.2.tar.gz";
      sha256 = "1r9sq30xz3jrvx6yqssj5wmkml1f75rx1amd7g89f3ryngrq6m59";
    };
  };
  "appscale-tools" = super.buildPythonPackage {
    name = "appscale-tools-3.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."adal"
      self."azure"
      self."azure-common"
      self."cryptography"
      self."argparse"
      self."boto"
      self."google-api-python-client"
      self."haikunator"
      self."httplib2"
      self."msrest"
      self."msrestazure"
      self."oauth2client"
      self."PyYAML"
      self."requests"
      self."retrying"
      self."setuptools"
      self."SOAPpy"
      self."tabulate"
      self."termcolor"
      self."wstools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/6f/c918723e0e240bcac028cef804c6874234c9096892fe9e489182ced08d28/appscale-tools-3.5.0.tar.gz";
      sha256 = "0c5f395ygqhlqfi77jhpapviglmmhs1ajgpgw45iz9qaavgfc76i";
    };
  };
  "argparse" = super.buildPythonPackage {
    name = "argparse-1.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/dd/e617cfc3f6210ae183374cd9f6a26b20514bbb5a792af97949c5aacddf0f/argparse-1.4.0.tar.gz";
      sha256 = "1r6nznp64j68ih1k537wms7h57nvppq0szmwsaf99n71bfjqkc32";
    };
  };
  "asn1crypto" = super.buildPythonPackage {
    name = "asn1crypto-0.23.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/53/8bca924b30cb79d6d70dbab6a99e8731d1e4dd3b090b7f3d8412a8d8ffbc/asn1crypto-0.23.0.tar.gz";
      sha256 = "0w2dv6ll5bsarkpn753c0bms1whkx4b3sk2qsrkb7syg549rhx08";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-17.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8b/0b/a06cfcb69d0cb004fde8bc6f0fd192d96d565d1b8aa2829f0f20adb796e5/attrs-17.4.0.tar.gz";
      sha256 = "1jafnn1kzd6qhxgprhx6y6ik1r5m2rilx25syzcmq03azp660y8w";
    };
  };
  "azure" = super.buildPythonPackage {
    name = "azure-2.0.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt"
      self."azure-batch"
      self."azure-servicebus"
      self."azure-storage"
      self."azure-servicemanagement-legacy"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/5c/d4a19612a2ca66966267198cd238ecc5e99e2082a41f0344733c7302ca92/azure-2.0.0rc6.zip";
      sha256 = "096kdg6iny9zpaciic0rhak1916jjw2f10hp0mb6sglg5y5a27yp";
    };
  };
  "azure-batch" = super.buildPythonPackage {
    name = "azure-batch-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-nspkg"
      self."azure-common"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/e9/6c16410251d9e65e89a8f72f6c5bcb3b8b54928a072e9481eccebd9c1cd4/azure-batch-1.0.0.zip";
      sha256 = "0gifk3xswgc6mr1xw0dv6jrq0v5vv2k8ljhclgqizyly7y33p1hc";
    };
  };
  "azure-common" = super.buildPythonPackage {
    name = "azure-common-1.1.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-nspkg"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/39/7b915a03e1a64415c81a8b8f317556182592327d2b62812ef2b19e71b378/azure-common-1.1.4.zip";
      sha256 = "0bqmzx26x4xy5qnd0687j1w7r0ja1sfc70bhgnj05qkx19yxkj7q";
    };
  };
  "azure-mgmt" = super.buildPythonPackage {
    name = "azure-mgmt-0.30.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-batch"
      self."azure-mgmt-redis"
      self."azure-mgmt-logic"
      self."azure-mgmt-scheduler"
      self."azure-mgmt-compute"
      self."azure-mgmt-keyvault"
      self."azure-mgmt-network"
      self."azure-mgmt-resource"
      self."azure-mgmt-storage"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/4a/1812c3d233e3d2e62613337552be64022dc4b231a5d51e25266cc68ddb33/azure-mgmt-0.30.0rc6.zip";
      sha256 = "1f5rrwn7dv677r9jm0kw79rqv658f0fr4m42kgabq6y5pj3w3c5k";
    };
  };
  "azure-mgmt-batch" = super.buildPythonPackage {
    name = "azure-mgmt-batch-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-nspkg"
      self."azure-common"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/15/315e59a9a3c7db95c9d653cec963d6dbb935a11335b5679aecf229d600f5/azure-mgmt-batch-1.0.0.zip";
      sha256 = "1sz5hcaxjr35v90ibid93z55gsn7qnjvz0n47vvwmjlczw57bxrs";
    };
  };
  "azure-mgmt-compute" = super.buildPythonPackage {
    name = "azure-mgmt-compute-0.30.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-nspkg"
      self."azure-common"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/b5/e85d7054f2ef45f4413e6711837d5dc3ac85ac3114cf3891e8938ecc40d5/azure-mgmt-compute-0.30.0rc6.zip";
      sha256 = "0xwd6ipn8yvdr3xhhrjmw459lvkph8p4kwjklw4waynwj1khgv01";
    };
  };
  "azure-mgmt-keyvault" = super.buildPythonPackage {
    name = "azure-mgmt-keyvault-0.30.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-common"
      self."azure-mgmt-nspkg"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/d8/bf649497dc0e589920393f6a3b9be3bec7eeea38c1f41d4476a5e828585b/azure-mgmt-keyvault-0.30.0rc6.zip";
      sha256 = "16m1qar7w9536xl6d3w5sbgl1wlzkb4yqlq60gjqj26frdi9l7n0";
    };
  };
  "azure-mgmt-logic" = super.buildPythonPackage {
    name = "azure-mgmt-logic-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-common"
      self."azure-mgmt-nspkg"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/16/32ef7f8cae08a7d2c7bd096c5d9f3af2fd96de23d3f8db337333401d8b36/azure-mgmt-logic-1.0.0.zip";
      sha256 = "01v0dwcnv8h4rlic5xs9payfrn7vgly8gqs1lvvyb9mir85wivqj";
    };
  };
  "azure-mgmt-network" = super.buildPythonPackage {
    name = "azure-mgmt-network-0.30.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-nspkg"
      self."azure-common"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/54/1459f5652fe19da9689bf8642f84fe220f6307dac8ac2a62e2b9f582eaa2/azure-mgmt-network-0.30.0rc6.zip";
      sha256 = "03w7jpps2045ppdnqmyyqnxwrc3m117yi3bzyj4j3pqa8yfq9c9i";
    };
  };
  "azure-mgmt-nspkg" = super.buildPythonPackage {
    name = "azure-mgmt-nspkg-2.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-nspkg"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/66/66eb0d5ead69b7371649466fa160a166de0d1ddafc4a1d7a172858a8abc9/azure-mgmt-nspkg-2.0.0.zip";
      sha256 = "0vrycmdgqz7z0qfhakmzr5hgsj0l11pyirn3bkpnimnpypa8hr73";
    };
  };
  "azure-mgmt-redis" = super.buildPythonPackage {
    name = "azure-mgmt-redis-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-common"
      self."azure-mgmt-nspkg"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/bc/b42afac6ff6479c95d8d5a0946f0c94f818a2cecb84303482eecf0d41f40/azure-mgmt-redis-1.0.0.zip";
      sha256 = "1bfv4w7cmiy3szs22v61vkkn5kiy9hfr0mqpvr716mk7wrbdxhdm";
    };
  };
  "azure-mgmt-resource" = super.buildPythonPackage {
    name = "azure-mgmt-resource-0.30.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-nspkg"
      self."azure-common"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5a/88/12b179f4473b51b671a126741b4520edbfea164bf0d683d3a0c78cec98a9/azure-mgmt-resource-0.30.0rc6.zip";
      sha256 = "10vkxlin8fbrfwcl3za8gvfdwjxd3qv3sgz60i2w0s54q33nmhmg";
    };
  };
  "azure-mgmt-scheduler" = super.buildPythonPackage {
    name = "azure-mgmt-scheduler-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-common"
      self."azure-mgmt-nspkg"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/42/4b15b354a2208e1fa43c327fd5a3215071140467624d3a14d97076988d7d/azure-mgmt-scheduler-1.0.0.zip";
      sha256 = "1hr2lg3g1i0c05xfbmfbq3qczw1a9dh7b8ri51w80wd2wng4ppxx";
    };
  };
  "azure-mgmt-storage" = super.buildPythonPackage {
    name = "azure-mgmt-storage-0.30.0rc6";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-mgmt-nspkg"
      self."azure-common"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/d8/425dc59243cca1e907778445d68610345fda4ff341b12209d4d4bb3d1388/azure-mgmt-storage-0.30.0rc6.zip";
      sha256 = "0rasspwsy02i9knizryc5xa5lsj2s2qg9k3sjbpnsviql6d6cf40";
    };
  };
  "azure-nspkg" = super.buildPythonPackage {
    name = "azure-nspkg-2.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/a2/77820fa07ec4657d6456b67edfa78856b4789ada42d1bb8e8485df19824e/azure-nspkg-2.0.0.zip";
      sha256 = "0yyw3wcy7xkrxwg7150a1wivgzwwyl877z2p4pv8xvk6iifyw6gy";
    };
  };
  "azure-servicebus" = super.buildPythonPackage {
    name = "azure-servicebus-0.20.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-common"
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/97/a0f9a44d2c9501329338ae252794c12939e70188a41d902c2717f26f7385/azure-servicebus-0.20.3.zip";
      sha256 = "1xw4frl7f3sn9nf2nil1y88p2alizyy06pppf7pxlv18696z8as4";
    };
  };
  "azure-servicemanagement-legacy" = super.buildPythonPackage {
    name = "azure-servicemanagement-legacy-0.20.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-common"
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/72/247d6e15711ace1e0e680d067f34e04facb3bc4b340234c0267b54842b01/azure-servicemanagement-legacy-0.20.4.zip";
      sha256 = "0ci9gwg6qr3j677h4f75kp05rpz65lfqax7rk8yh7zv5c1szhbbl";
    };
  };
  "azure-storage" = super.buildPythonPackage {
    name = "azure-storage-0.33.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."azure-nspkg"
      self."azure-common"
      self."cryptography"
      self."python-dateutil"
      self."requests"
      self."futures"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/fd/301d5d72126125b59731ad64bcfcc9bc75fcddb9bb8370a917559a693433/azure-storage-0.33.0.zip";
      sha256 = "0h1cah922xf7jahbw0fdq09xwqciifa0dv1g8527z6v9vmdy25qi";
    };
  };
  "backports.ssl-match-hostname" = super.buildPythonPackage {
    name = "backports.ssl-match-hostname-3.5.0.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/21/2dc61178a2038a5cb35d14b61467c6ac632791ed05131dda72c20e7b9e23/backports.ssl_match_hostname-3.5.0.1.tar.gz";
      sha256 = "1wndipik52cyqy0677zdgp90i435pmvwd89cz98lm7ri0y3xjajh";
    };
  };
  "bcrypt" = super.buildPythonPackage {
    name = "bcrypt-3.1.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/ec/bb6b384b5134fd881b91b6aa3a88ccddaad0103857760711a5ab8c799358/bcrypt-3.1.4.tar.gz";
      sha256 = "13cyrnqwkhc70rs6dg65z4yrrr3dc42fhk11804fqmci9hvimvb7";
    };
  };
  "blinker" = super.buildPythonPackage {
    name = "blinker-1.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/66/c15dbe2e2cac59bf1d4670d52aa88b8746fd5a47f8353aa4ffac0dde00c4/blinker-1.3.tar.gz";
      sha256 = "0bvfxkmjx6bpa302pv7v2vw5rwr3dlzjzfdp3bj628i6144024b8";
    };
  };
  "boto" = super.buildPythonPackage {
    name = "boto-2.48.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/66/e7/fe1db6a5ed53831b53b8a6695a8f134a58833cadb5f2740802bc3730ac15/boto-2.48.0.tar.gz";
      sha256 = "1l80f1njpdkvzvs6z4abixskhqwr31h8arfywdwrc42bfddr5f6y";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2018.1.18";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/d4/2f888fc463d516ff7bf2379a4e9a552fef7f22a94147655d9b1097108248/certifi-2018.1.18.tar.gz";
      sha256 = "0z9zyry30znikglm66d3r9y0yaqa2sxr4xlsyxqzbvi76hh3zg7d";
    };
  };
  "cffi" = super.buildPythonPackage {
    name = "cffi-1.10.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pycparser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/b9/790f8eafcdab455bcd3bd908161f802c9ce5adbf702a83aa7712fcc345b7/cffi-1.10.0.tar.gz";
      sha256 = "1mffyilq4qycm8gs4wkgb18rnqil8a9blqq77chdlshzxc8jkc5k";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "click" = super.buildPythonPackage {
    name = "click-6.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/d9/c3336b6b5711c3ab9d1d3a80f1a3e2afeb9d8c02a7166462f6cc96570897/click-6.7.tar.gz";
      sha256 = "02qkfpykbq35id8glfgwc38yc430427yd05z1wc5cnld8zgicmgi";
    };
  };
  "configobj" = super.buildPythonPackage {
    name = "configobj-5.0.6";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz";
      sha256 = "00h9rcmws03xvdlfni11yb60bz3kxfvsj6dg6nrpzj71f03nbxd2";
    };
  };
  "configparser" = super.buildPythonPackage {
    name = "configparser-3.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz";
      sha256 = "0fi7vf09vi1588jd8f16a021m5y6ih2hy7rpbjb408xw45qb822k";
    };
  };
  "contexter" = super.buildPythonPackage {
    name = "contexter-0.1.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/8e/fa97d40616c8d1bda8f83b12ab0ccf9fe0420cb89cf73184436bd3c581fe/contexter-0.1.4.tar.gz";
      sha256 = "1a50bqqbzf9hvggblmppv00pvjnx3kmdhl33990m2l4i385qjc67";
    };
  };
  "cryptography" = super.buildPythonPackage {
    name = "cryptography-2.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."idna"
      self."asn1crypto"
      self."six"
      self."enum34"
      self."ipaddress"
      self."cffi"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0a/23/ffee389a45f752dc745706cdb2d354b91ddb71594506fac45236cf67af49/cryptography-2.0.2.tar.gz";
      sha256 = "1aq6ilnf2zdqshwqai4w8gmb5y6p7ip34qrjp1yb7sz77rkb501p";
    };
  };
  "cssmin" = super.buildPythonPackage {
    name = "cssmin-0.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8e/d8/dc9da69bb186303f7ab41adef0a5b6d34da2fdba006827620877760241c3/cssmin-0.2.0.tar.gz";
      sha256 = "1dk723nfm2yf8cp4pj785giqlwv42l0kj8rk40kczvq1hk6g04p0";
    };
  };
  "cssselect" = super.buildPythonPackage {
    name = "cssselect-0.9.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/21/47b5d2696a945da177d2344b6e330b7b0d1c52404063cb387d2261517ccb/cssselect-0.9.2.tar.gz";
      sha256 = "1xg6gbva1yswghiycmgincv6ab4bn7hpm720ndbj40h8xycmnfvi";
    };
  };
  "defusedxml" = super.buildPythonPackage {
    name = "defusedxml-0.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/ba/4ba4e89e21b5a2e267d80736ea674609a0a33cc4435a6d748ef04f1f9374/defusedxml-0.5.0.tar.gz";
      sha256 = "1x54n0h8hl92vvwyymx883fbqpqjwn2mc8fb383bcg3z9zwz5mr4";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.13.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad6e19da8d08895ae/docutils-0.13.1.tar.gz";
      sha256 = "1gkma47i609jfs7dssxn4y9vsz06qi0l5q41nws0zgkpnrghz33i";
    };
  };
  "entrypoints" = super.buildPythonPackage {
    name = "entrypoints-0.2.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."configparser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/e8/607697e6ab8a961fc0b141a97ea4ce72cd9c9e264adeb0669f6d194aa626/entrypoints-0.2.3.tar.gz";
      sha256 = "17q21k8igjb47b73jn4w6lgzza1nscn3sf1sn5gm96bgw3fqgmfj";
    };
  };
  "enum34" = super.buildPythonPackage {
    name = "enum34-1.1.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz";
      sha256 = "1cgm5ng2gcfrkrm3hc22brl6chdmv67b9zvva9sfs7gn7dwc9n4a";
    };
  };
  "feedgenerator" = super.buildPythonPackage {
    name = "feedgenerator-1.9";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/02/7069b3dbc6ea92f034e07f9f9adc2193cd02d1aedf2cf9ec71150102a964/feedgenerator-1.9.tar.gz";
      sha256 = "01mirwkm7xfx539hmvj7g9da1j51gw5lsx74dr0glizskjm5vq2s";
    };
  };
  "feedparser" = super.buildPythonPackage {
    name = "feedparser-5.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/d8/7d37fec71ff7c9dbcdd80d2b48bcdd86d6af502156fc93846fb0102cb2c4/feedparser-5.2.1.tar.bz2";
      sha256 = "00hb4qg2am06g81mygfi1jsbx8830024jm45g6qp9g8fr6am91yf";
    };
  };
  "futures" = super.buildPythonPackage {
    name = "futures-3.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/9e/7b2ff7e965fc654592269f2906ade1c7d705f1bf25b7d469fa153f7d19eb/futures-3.2.0.tar.gz";
      sha256 = "0rdjmmsab550kxsssdq49jcniz77zlkpw4pvi9hvib3lsskjmh4y";
    };
  };
  "google-api-python-client" = super.buildPythonPackage {
    name = "google-api-python-client-1.5.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."httplib2"
      self."oauth2client"
      self."six"
      self."uritemplate"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/c4/c77f3ddadf17d041f237615d5fba02faefd93adfb82ad75877156647491a/google-api-python-client-1.5.4.tar.gz";
      sha256 = "1b09f3llgfq52l6ksw2r3gkk29cs3y7m260w4kl5dmfjz5y6kxmr";
    };
  };
  "haikunator" = super.buildPythonPackage {
    name = "haikunator-2.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/58/6a000ee0ec34cac5c78669359a8b1db969f1f511454a140ad3d193714ba2/haikunator-2.1.0.zip";
      sha256 = "16zzfpf5v7g46qa4j4bb6x4f4qkhn4b0ppnx6z0cl4x6ld4kkvli";
    };
  };
  "html5lib" = super.buildPythonPackage {
    name = "html5lib-0.999999999";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/17/ee/99e69cdcefc354e0c18ff2cc60aeeb5bfcc2e33f051bf0cc5526d790c445/html5lib-0.999999999.tar.gz";
      sha256 = "1632ak23y4j78jdm24s6iqyf2kzfcmf6p4v141rd4a1hzl7pqx7f";
    };
  };
  "htmlmin" = super.buildPythonPackage {
    name = "htmlmin-0.1.12";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/e7/fcd59e12169de19f0131ff2812077f964c6b960e7c09804d30a7bf2ab461/htmlmin-0.1.12.tar.gz";
      sha256 = "0y51xhabw6x8jk8k93xl8vznshpz3jb6l28075r5sjip613fzhah";
    };
  };
  "httplib2" = super.buildPythonPackage {
    name = "httplib2-0.10.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/2e/a7e27d2c36076efeb8c0e519758968b20389adf57a9ce3af139891af2696/httplib2-0.10.3.tar.gz";
      sha256 = "1syfnfmh7685n65in57gvjka7mh52dy8w286369vrhc6pnvx6174";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/82/28a51052215014efc07feac7330ed758702fc0581347098a81699b5281cb/idna-2.5.tar.gz";
      sha256 = "1ara12a7k2zc69msa0arrvw00gn61a6i6by01xb3lkkc0h4cxd9w";
    };
  };
  "ipaddress" = super.buildPythonPackage {
    name = "ipaddress-1.0.18";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/13/774faf38b445d0b3a844b65747175b2e0500164b7c28d78e34987a5bfe06/ipaddress-1.0.18.tar.gz";
      sha256 = "1q8klj9d84cmxgz66073x1j35cplr3r77vx1znhxiwl5w74391ax";
    };
  };
  "isodate" = super.buildPythonPackage {
    name = "isodate-0.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/80/fb8c13a4cd38eb5021dc3741a9e588e4d1de88d895c1910c6fc8a08b7a70/isodate-0.6.0.tar.gz";
      sha256 = "1n7jkz68kk5pwni540pr5zdh99bf6ywydk1p5pdrqisrawylldif";
    };
  };
  "jmespath" = super.buildPythonPackage {
    name = "jmespath-0.9.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8f/d8/6e3e602a3e90c5e3961d3d159540df6b2ff32f5ab2ee8ee1d28235a425c1/jmespath-0.9.0.tar.gz";
      sha256 = "0g9xvl69y7nr3w7ag4fsp6sm4fqf6vrqjw7504x2hzrrsh3ampq8";
    };
  };
  "joblib" = super.buildPythonPackage {
    name = "joblib-0.11";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/ec/538d50a72046e733b91a5c1fc9456d33e5cb830355317348775fa73f1ac4/joblib-0.11.tar.gz";
      sha256 = "11a0xl00q8kp3bmms9cn5bv03d53hp5mqf996yl335vdydnxb3vv";
    };
  };
  "keyring" = super.buildPythonPackage {
    name = "keyring-12.0.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."entrypoints"
      self."secretstorage"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/f5/26c0d2195b2d3c2f3ecf11eff0903d5eca3a53d3999da2a7d4a2035cc769/keyring-12.0.1.tar.gz";
      sha256 = "1g9s66xa0ak7p8yg71kn6w0ld3r2nlcyras4ajn3n871krq9qv44";
    };
  };
  "lxml" = super.buildPythonPackage {
    name = "lxml-4.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/4c/d83979fbc66a2154850f472e69405572d89d2e6a6daee30d18e83e39ef3a/lxml-4.1.1.tar.gz";
      sha256 = "03pls37saf45s91qdizz2llh5wnh8bz98sqg9g1y0y3wxkqsw34l";
    };
  };
  "mdx-video" = super.buildPythonPackage {
    name = "mdx-video-0.1.8";
    doCheck = false;
    propagatedBuildInputs = [
      self."Markdown"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/7d/87affe59f05aa62717b5ef7a79af57e6725c3cdf089e6b0f5d422a73e09b/mdx_video-0.1.8.tar.gz";
      sha256 = "11yrb7ncpmsb84f04qkx63xjwjxmfgn2511xdr2ihbz48c6x3n0p";
    };
  };
  "msrest" = super.buildPythonPackage {
    name = "msrest-0.4.27";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
      self."requests-oauthlib"
      self."isodate"
      self."certifi"
      self."enum34"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/51/5c57754bfb2c097f5057c11a712d7b45f9a7f78191085085d3f34c809c4f/msrest-0.4.27.tar.gz";
      sha256 = "0fd7nf81kgkxkyqlyz7pgia91c1hym97afz0y2156pp4fcnz0ifg";
    };
  };
  "msrestazure" = super.buildPythonPackage {
    name = "msrestazure-0.4.19";
    doCheck = false;
    propagatedBuildInputs = [
      self."msrest"
      self."keyring"
      self."adal"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6a/d1/761e69540cc8076a8a64f280638397e2eb1dcba1ff697e5cd1730797eff9/msrestazure-0.4.19.tar.gz";
      sha256 = "1i3921lnzkx8xva9czhhz2rfpqhx5jyibrnyq542nxrjlhjqzds3";
    };
  };
  "mutagen" = super.buildPythonPackage {
    name = "mutagen-1.39";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/cb/df5b1ed5276d758684b245ecde990b05ea7470d4fa9530deb86a24cf723b/mutagen-1.39.tar.gz";
      sha256 = "1r0ri97f3pqlxhs8fyrrlw11zn4gmamnfqfjzwc5dzlg8mk2bacx";
    };
  };
  "nose" = super.buildPythonPackage {
    name = "nose-1.3.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz";
      sha256 = "164a43k7k2wsqqk1s6vavcdamvss4mz0vd6pwzv2h9n8rgwzxgzi";
    };
  };
  "numpy" = super.buildPythonPackage {
    name = "numpy-1.13.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/2d/005e45738ab07a26e621c9c12dc97381f372e06678adf7dc3356a69b5960/numpy-1.13.3.zip";
      sha256 = "0l576ngjbpjdkyja6jd16znxyjshsn9ky1rscji4zg5smpaqdvin";
    };
  };
  "oauth2client" = super.buildPythonPackage {
    name = "oauth2client-4.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."httplib2"
      self."pyasn1"
      self."pyasn1-modules"
      self."rsa"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/ce/7aaf19d8b856191e2e1885201fe45f3dc57b97f5ec5bc98ef2cc15472918/oauth2client-4.0.0.tar.gz";
      sha256 = "1irqqap2zibysf8dba8sklfqikia579srd0phm5n754ni0h59gl0";
    };
  };
  "oauthlib" = super.buildPythonPackage {
    name = "oauthlib-2.0.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/b9/66278631430fe688b2e6c84df16619f1d1e27c9c6ebca28371f7c6fbb346/oauthlib-2.0.7.tar.gz";
      sha256 = "0235fnxc0wfx56jj33npqb443vgjfpc4dh8lk7z13yimfqlnb5lh";
    };
  };
  "olefile" = super.buildPythonPackage {
    name = "olefile-0.45.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d3/8a/e0f0e56d6a542dd987f9290ef7b5164636ee597ce8c2932c19c78292d5ec/olefile-0.45.1.zip";
      sha256 = "11fkg10fdxns7dww3iw2yrd8iq7pj42lkigqhq8aps0d57spar9b";
    };
  };
  "paramiko" = super.buildPythonPackage {
    name = "paramiko-2.3.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."bcrypt"
      self."cryptography"
      self."PyNaCl"
      self."pyasn1"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/a9/3a644f56aecc46dd0ff404a2d1d963e713c5e371c060337de4301dca19d9/paramiko-2.3.2.tar.gz";
      sha256 = "0pa10cx1ybgiqfp1v1ywxxx5l5rl2fchyq279n0bh4iijklyg0cb";
    };
  };
  "pbr" = super.buildPythonPackage {
    name = "pbr-3.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/d6/f2bf137d71e4f213b575faa9eb426a8775732432edb67588a8ee836ecb80/pbr-3.1.1.tar.gz";
      sha256 = "1qavz7bmhqcyfqj67dxk53m2dxazh6wyx8y06y72vh7gm9qirxh5";
    };
  };
  "pelican" = super.buildPythonPackage {
    name = "pelican-3.7.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."feedgenerator"
      self."Jinja2"
      self."Pygments"
      self."docutils"
      self."pytz"
      self."blinker"
      self."unidecode"
      self."six"
      self."python-dateutil"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/9e/c5cf3f7e98b84ac666422d7f6707cc415d4c96247c266377c0ed5a489f49/pelican-3.7.1.tar.gz";
      sha256 = "12spygavv9b6xpb5pgp7f0p3z0mms60nx6zrpx1yfkj68zz4flra";
    };
  };
  "pelican-minify" = super.buildPythonPackage {
    name = "pelican-minify-0.9";
    doCheck = false;
    propagatedBuildInputs = [
      self."htmlmin"
      self."pelican"
      self."joblib"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/46/9956d4ef70ddf440e4f89a0fcb455eb8311eeddf7d7bbeb6fa6126ca5161/pelican-minify-0.9.tar.gz";
      sha256 = "0ww7fp3w8ai2nvcgyikrg916sdc7pbzcb4j6xi5br2ahy6qskzx0";
    };
  };
  "pip" = super.buildPythonPackage {
    name = "pip-9.0.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/44/e6b8056b6c8f2bfd1445cc9990f478930d8e3459e9dbf5b8e2d2922d64d3/pip-9.0.3.tar.gz";
      sha256 = "15jpxz282dfaxpk5b2ny3ikzsagyx457xbzp967xbq9vd6d8zx3v";
    };
  };
  "pip2nix" = super.buildPythonPackage {
    name = "pip2nix-0.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pip"
      self."configobj"
      self."click"
      self."contexter"
      self."Jinja2"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/b4/8bb100b5854edc58a39e43298481dbe4a495ae8ec053a4d14c4431b5f1fb/pip2nix-0.7.0.tar.gz";
      sha256 = "15bs75wpkn2rllnfg83fpwqw7ddp9qw8dly9nv3krx67kbh736pc";
    };
  };
  "ply" = super.buildPythonPackage {
    name = "ply-3.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/4d/487e12d0478ee0cbb15d6fe9b8916e98fe4e2fce4cc65e4de309209c0b24/ply-3.9.tar.gz";
      sha256 = "0gpl0yli3w03ipyqfrp3w5nf0iawhsq65anf5wwm2wf5p502jzhd";
    };
  };
  "praw" = super.buildPythonPackage {
    name = "praw-5.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."prawcore"
      self."update-checker"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/ec/086d6694614b767d811932d95ec17232cbef29ea2f10f1b8d5293cbc670e/praw-5.4.0.tar.gz";
      sha256 = "1dw00z4jy1lch9vrg6k596z2md2g0wyy45ksmv9cag9qh61i3p04";
    };
  };
  "prawcore" = super.buildPythonPackage {
    name = "prawcore-0.14.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/9d/032031a050a4e8f76c4a3a1220c94deb780c74e3b112ae00ebc28df8ccba/prawcore-0.14.0.tar.gz";
      sha256 = "0dwgrybclxms6mrwn76ba6qqqi6k46d33sp0ml9f478xikp34p6c";
    };
  };
  "pyOpenSSL" = super.buildPythonPackage {
    name = "pyOpenSSL-17.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/9e/7088f6165c40c46416aff434eb806c1d64ad6ec6dbc201f5ad4d0484704e/pyOpenSSL-17.2.0.tar.gz";
      sha256 = "0d283g4zi0hr9papd24mjl70mi15gyzq6fx618rizi87dgipqqax";
    };
  };
  "pyasn1" = super.buildPythonPackage {
    name = "pyasn1-0.3.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/a6/4d6c88aa1694a06f6671362cb3d0350f0d856edea4685c300785200d1cd9/pyasn1-0.3.7.tar.gz";
      sha256 = "0ra9mlf35v7bg9brv2m83mz2i868nwrh1h6mha73ys0psrk2lzqq";
    };
  };
  "pyasn1-modules" = super.buildPythonPackage {
    name = "pyasn1-modules-0.1.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."pyasn1"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/2c/351c0c0ef88b904de50d8144eb4c365c13660c297c051b72255b4e1ad34a/pyasn1-modules-0.1.5.tar.gz";
      sha256 = "1239h6h67vg0wazg2qgv6m3hdim2gs66pl89lbnayk55bbnkwc0x";
    };
  };
  "pycairo" = super.buildPythonPackage {
    name = "pycairo-1.15.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/19/fe55081365f01b862073c330ee97707afff21f4c0f6c0376f93819daa9f2/pycairo-1.15.3.tar.gz";
      sha256 = "17bi8i0a2agx52x67c1z0wyihpvgf46b9lk04z0bzb36xxnf6hl6";
    };
  };
  "pycparser" = super.buildPythonPackage {
    name = "pycparser-2.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz";
      sha256 = "0wvzyb6rxsfj3xcnpa4ynbh9qc7rrbk2277d5wqpphmx9akv8nbr";
    };
  };
  "pycrypto" = super.buildPythonPackage {
    name = "pycrypto-2.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz";
      sha256 = "0g0ayql5b9mkjam8hym6zyg6bv77lbh66rv1fyvgqb17kfc1xkpj";
    };
  };
  "pycryptopp" = super.buildPythonPackage {
    name = "pycryptopp-0.6.0.1206569328141510525648634803928199668821045408958";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/6b/5845a594602ef5274826a8a54ef8760530fb1c4a3e0f6d13490ea89e2a2f/pycryptopp-0.6.0.1206569328141510525648634803928199668821045408958.tar.gz";
      sha256 = "0n90h1yg7bfvlbhnc54xb6dbqm286ykaksyg04kxlhyjgf8mhq8i";
    };
  };
  "pyinotify" = super.buildPythonPackage {
    name = "pyinotify-0.9.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz";
      sha256 = "1x3i9wmzw33fpkis203alygfnrkcmq9w1aydcm887jh6frfqm6cw";
    };
  };
  "pyserial" = super.buildPythonPackage {
    name = "pyserial-3.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/d8/a9fa247ca60b02b3bebbd61766b4f321393b57b13c53b18f6f62cf172c08/pyserial-3.1.1.tar.gz";
      sha256 = "0k1nfdrxxkdlv4zgaqsdv8li0pj3gbh2pyxw8q2bsg6f9490amyn";
    };
  };
  "python-Levenshtein" = super.buildPythonPackage {
    name = "python-Levenshtein-0.12.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz";
      sha256 = "1c9ybqcja31nghfcc8xxbbz9h60s9qi12b9hr4jyl69xbvg12fh3";
    };
  };
  "python-dateutil" = super.buildPythonPackage {
    name = "python-dateutil-2.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/fc/39a3fbde6864942e8bb24c93663734b74e281b984d1b8c4f95d64b0c21f6/python-dateutil-2.6.0.tar.gz";
      sha256 = "1lhq0hxjc3cfha101q02ld5ijlpfyjn2w1yh7wvpiy367pgzi8k2";
    };
  };
  "python-keyczar" = super.buildPythonPackage {
    name = "python-keyczar-0.71rc0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pycrypto"
      self."pyasn1"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/1b/57dbd7bac8c6b9b5e497092da67535ed97b593373cf9cdd66c718f28de4c/python-keyczar-0.71c.tar.gz";
      sha256 = "18mhiwqq6vp65ykmi8x3i5l3gvrvrrr8z2kv11z1rpixmyr7sw1p";
    };
  };
  "pytz" = super.buildPythonPackage {
    name = "pytz-2017.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/09/c47e57fc9c7062b4e83b075d418800d322caa87ec0ac21e6308bd3a2d519/pytz-2017.2.zip";
      sha256 = "12cmd3j46d2gcw08bspvp6s9icfcvx88zjz52n1bli9dyvl5dh7m";
    };
  };
  "pyxdg" = super.buildPythonPackage {
    name = "pyxdg-0.25";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/28/ee953bd2c030ae5a9e9a0ff68e5912bd90ee50ae766871151cd2572ca570/pyxdg-0.25.tar.gz";
      sha256 = "179767h8m634ydlm4v8lnz01ba42gckfp684id764zaip7h87s41";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.19.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."chardet"
      self."idna"
      self."urllib3"
      self."certifi"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/1f/782a5734931ddf2e1494e4cd615a51ff98e1879cbe9eecbdfeaf09aa75e9/requests-2.19.1.tar.gz";
      sha256 = "0snf8xxdzsgh1x2zv3vilvbrv9jbpmnfagzzb1rjmmvflckdh8pc";
    };
  };
  "requests-oauthlib" = super.buildPythonPackage {
    name = "requests-oauthlib-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."oauthlib"
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/be/072464f05b70e4142cb37151e215a2037b08b1400f8a56f2538b76ca6205/requests-oauthlib-1.0.0.tar.gz";
      sha256 = "0gys581rqjdlv0whhqp5s2caxx66jzvb2hslxn8v7bypbbnbz1l8";
    };
  };
  "retrying" = super.buildPythonPackage {
    name = "retrying-1.3.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz";
      sha256 = "0fwp86xv0rvkncjdvy2mwcvbglw4w9k0fva25i7zx8kd19b3kh08";
    };
  };
  "rsa" = super.buildPythonPackage {
    name = "rsa-3.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."pyasn1"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/89/adf8b72371e37f3ca69c6cb8ab6319d009c4a24b04a31399e5bd77d9bb57/rsa-3.4.2.tar.gz";
      sha256 = "1dcxvszbikgzh99ybdc7jq0zb9wspy2ds8z9mjsqiyv3q884xpr5";
    };
  };
  "secretstorage" = super.buildPythonPackage {
    name = "secretstorage-2.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."cryptography"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/a5/0830cfe34a4cfd0d1c3c8b614ede1edb2aaf999091ac8548dd19cb352e79/SecretStorage-2.3.1.tar.gz";
      sha256 = "1di9gx4m27brs6ar774m64s017iz742mnmw39kvfc8skfs3mrxis";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-39.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/04/d6f1159feaccdfc508517dba1929eb93a2854de729fa68da9d5c6b48fa00/setuptools-39.2.0.zip";
      sha256 = "1cigcz8x2gf3lb43y63apxqgl0bpky26xaqfn0g32h66ynsxpkgp";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.11.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  "tabulate" = super.buildPythonPackage {
    name = "tabulate-0.7.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/a1/3367581782ce79b727954f7aa5d29e6a439dc2490a9ac0e7ea0a7115435d/tabulate-0.7.7.tar.gz";
      sha256 = "1inqhspd4frxnp08c32yndr0lc4px1xfkqah184i5w09gkhvi843";
    };
  };
  "termcolor" = super.buildPythonPackage {
    name = "termcolor-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz";
      sha256 = "0fv1vq14rpqwgazxg4981904lfyp84mnammw7y046491cv76jv8x";
    };
  };
  "unidecode" = super.buildPythonPackage {
    name = "unidecode-1.0.22";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/36/49d0ee152b6a1631f03a541532c6201942430060aa97fe011cf01a2cce64/Unidecode-1.0.22.tar.gz";
      sha256 = "1xdbxx31fir6di5d86qk4vvm2j23llawg87afqmc56qcircdscwc";
    };
  };
  "update-checker" = super.buildPythonPackage {
    name = "update-checker-0.16";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/17/35d8c5cf206b2840fec39bf33c3817aec0320433f8de574441468a632e99/update_checker-0.16.tar.gz";
      sha256 = "1f38l40d32dm0avcidf3dmikma8z0la84yngj88v4xygzi399qvh";
    };
  };
  "uritemplate" = super.buildPythonPackage {
    name = "uritemplate-3.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/db/f7b98cdc3f81513fb25d3cbe2501d621882ee81150b745cdd1363278c10a/uritemplate-3.0.0.tar.gz";
      sha256 = "0781gm9g34wa0asc19dx81ng0nqq07igzv3bbvdqmz13pv7469n0";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.23";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3c/d2/dc5471622bd200db1cd9319e02e71bc655e9ea27b8e0ce65fc69de0dac15/urllib3-1.23.tar.gz";
      sha256 = "1bvbd35q3zdcd7gsv38fwpizy7p06dr0154g5gfybrvnbvhwb2m6";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "wstools" = super.buildPythonPackage {
    name = "wstools-0.4.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/a3/0fbea78bccec0970032b847135b0d6050224c8601460464edcc748c5a22c/wstools-0.4.3.tar.gz";
      sha256 = "1y1n0g9x4il67vr8664zc2aaadwvzmczblfzamddznn8iglm72sp";
    };
  };

### Test requirements

  
}
