
Got the insperation for a webise from 
[[http://creativecommons.org/licenses/by-sa/4.0/][eevee]]

So this is powered by [[http://docs.getpelican.com/en/stable/][pelican]].
(and the org-mode plugin, org mode best mode)


* TODO website extensions

+ Reddit comments into static site
+ Justify paragraphs like latex

** Org export
+ Should be faster
  + Maybe going full python? IDK how far that is or how much work
+ TOC shouldn't be generated with ID on overview page.
** Layout ideas

*** Body based wrapping
http://benhoyt.com/writings/pyast64/

Also looks really clean.
Although the word spacing is a weird choice

** Speedup
Load logo seperatly,
or do inpage compression,
It seems to be about 100k now which is a bit much imho.

** NGINX
*** tracking
1. Should move configuration file into the version controll
2. Publish script should overwrite the config file from version controlled one

*** redericts
Make them all temporary, don't want browsers to cache them.


** Search performance
*** TODO Setup amp?
*** TODO Setup structured
* Troubleshooting
  To help me trough the dark times when the ductape fails.
  
** Org fails
   Probably because of that orgmode bug where they say it isn't allowed to do
   compilation. (the id then doesn't get generated which makes it fail entrily).
   Test by trying to just =C-c C-c= some random org source block.
   Try recompiling elpa =m x recompile-elpa= and see if it loads now.
   
*** wrong type arg (stringp, null)
If it's only the thesis it's the plant uml blocks. recompile elpa,
make sure plantuml is enable (should be).

Also I found a binary search was a good way to confirm that it's the plantuml
blocks.

** Assets not found in template
   Set the =SASS_PATH= to theme/static/css.
   
** Web assets doesn't render
   Mask jinja 2.9 for webassets 0.12, see https://bugs.gentoo.org/641766

* Links
[[https://www.google.com/webmasters/tools/site-message-view?hl=en_GB&authuser=0&siteUrl=https://jappieklooster.nl/][Google crawl report]], I stumbled on that when configuring a static site in
buckets.
