# Use org mode because of the toc
#+TITLE: Endorsement
#+DATE: 2017-06-28
#+Modified: 2019-04-5 11:27
#+CATEGORY: meta
#+Tags: tips, remind, hastag
A post I'll periodicly update (no promises)
of links I've found that are interesting, funny whatever.
I guess its a +hall+ wall of fame of sorts except it has zero prestige.
(well maybe some day it will).
It also serves as a kindoff reminder of stuff I used to like.
 
* Beauty
** A work of art
   https://aphyr.com/posts/342-typing-the-technical-interview
   I'm envious if the writing style in that blog post.
   It weaves together some extremely advanced type level programming
   with a funny narrative.
   I hope that I could produce this kind of writing in the future too.

** Wallpapers
http://www.erikjohanssonphoto.com/
I used several images as wallpapers from this guy, at the time I couldn't
pay him so I guess I repay him by giving him some realestate on my website.

* Funny
** Suicide linux
 I remember a script that would execute =rm -rf /= if you'd type a command incorrectly,
 just to teach you to be precise. 
 It was [[https://qntm.org/suicide][sucide linux]].

 I'm not running that.

* Interesting

** Suckless
   It's software that sucks slightly less.
    http://suckless.org/

   Amongst other things they have a irc client
   that works with fifo queues on the filesystem.
   It's beautifull.

** Tsoding
   A [[https://www.twitch.tv/tsoding][streamer]] who makes a show of programming.
   With the slogan 'coding for fun' he
   traverses the programming landscape from
   [[https://github.com/tsoding/HyperNerd][haskell]] to [[https://github.com/tsoding/wassm][assembly]] and
   from [[https://github.com/tsoding/HyperNerd/blob/master/src/Markov.hs][markov chains]] to [[https://github.com/tsoding/grub-gamepad][grub drivers]].

** CGPGrey
A youtuber, although I'm linking to his [[http://www.cgpgrey.com/][website]].
He has some interesting videos (of which I know him),
but his podcasts are quite good too.

** Brady haron
Also a youtber, [[http://www.bradyharan.com/][his website]]. His numberphile channel is fun.
** How computers learn
A back to basics overview of machine learning:
https://youtu.be/T1O3ikmTEdA?t=644

Even though I knew most stuff he talked about in the beginning,
the talk later becomes more interesting since I didn't follow machine learning
that much.



** Tech blogs
   At some point I wanted to read interesting soemthing interesting,
   I found these who look all very interesting:
   + https://blog.acolyer.org/
   + http://highscalability.com/
   + https://rachelbythebay.com/w/

** Techstratery
This guy is some kindoff analist I encountered on reddit
(probably the /r/investing sub).
He has some really interesting takes on tech companies and I learned a lot about
buisness in general from just reading his blog.
I especially liked his aggregration theory, makes me wonder if I could make one
of those.. (probably not).
https://stratechery.com/

** danluu
I found one of his articles on reddit, and he has an interesting perspective
(as moslty a hardware person).
I was reading the article [[https://danluu.com/wat/][normalization of defiance]] which talks about how
strange, shady or broken practices are born, and what one could do about them.
Then I went to the index and it turns out there is a huge treasure trove
of interesting articles on that blog.

https://danluu.com/


** Philosophize this
   I really enjoyed this [[http://philosophizethis.org/][podcast]].
   He goes trough all great philosphors in chronoloigical
   order, which as a side effect helps you understand
   history better.
   It also made me think about my own life.

** xoreaxeaxeax
Everything in [[https://github.com/xoreaxeaxeax/][this github]] profile page is +insane+ beautifull.
[[https://www.youtube.com/watch?v=KrksBdWcZgQ&feature=youtu.be&t=1250][This youtube]] explains the sandsifter thing in quite detail.

* Reading
** Books in public domain
   I've been reading the 'classics', of which many are in public domain.
   No need to spend precious money on something which ought to be free.
   Project gutenberg offers public domain ebooks for free:
   - https://www.gutenberg.org/
     
   I do recommend donating to them though. [[https://www.gutenberg.org/wiki/Gutenberg:Project_Gutenberg_Literary_Archive_Foundation][They're doing important work]].
** Programming for personal growth
A really well written article about how simple satisfication
(with programming in this case) may make you more confident and happy in life:
https://medium.com/the-polymath-project/programming-for-personal-growth-64052e407894

** Writing well by george orwell
http://www.orwell.ru/library/essays/politics/english/e_polit

Any one interested in writing demands a read of that.
It describes why texts are interesting or not.
It suggests for example that each sentence should anwser these questions:

+ What am I trying to say?
+ What words will express it?
+ What image or idiom will make it clearer?  
+ Is this image fresh enough to have an effect?
+ Could I put it more shortly?
+ Have I said anything that is avoidably ugly?

It also explains why we see this horrible accedemic style such as:
"If a new spirit is to be infused into this old country, there is one thorny and contentious reform which must be tackled, and that is the humanization and galvanization..."

** Paul graham essays
   [[http://www.paulgraham.com/articles.html][These]] are both inspiring as interesting.
   I've found myself identifying with much he wrote
   about.
   Especially now I've decided to start my own startup,
   it's really motivating,
   although I know he writes those mostly to just get
   more candidates to chose from.
   I like to believe he also does it to genuinly help people.
   Getting a job is bad for your brainz.

* Tools
** Vps comparison sites
For if you just need a cheap computing device somewhere on the internet.
I wanted one that had high CPU but didn't care about the rest, this one found
it:
http://vps-list.cryto.net/index.php?action=list

** Haskell blogposts
   + [[https://kodimensional.dev/posts/2019-03-25-comonadic-builders][Comonads for builders]].
   
* Anime
  I watch way to much anime.
  Sometimes I encounter little gems, recorded here.

** Puella Magi Madoka Magica
   A beautifull juxtposition of childishness and despair.
   I don't want to say anything because I'll spoil it but give it a try,
   it's so worth it.
   
** Code geass
   This was one of my first gateway anime drugs.
   It's an excellent classic keeping you on the edge of the seat all the way.
   All characters have good motivations and are believeable.

** Soul eater
   I especially liked the first season, it drags on for a bit
   after that. But the theme around crazy-ness being the 
   enemy is really appealing to me.
