# Use org mode because of the toc
#+TITLE: Endorsement
#+DATE: 2017-06-28
#+CATEGORY: meta
#+Tags: tips, remind, hastag
A post I'll periodicly update (no promises)
of links I've found that are interesting, funny whatever.
I guess its a +hall+ wall of fame of sorts except it has zero prestige.
(well maybe some day it will).
It also serves as a kindoff reminder of stuff I used to like.
 
* Beauty
** Wallpapers
http://www.erikjohanssonphoto.com/
I used several images as wallpapers from this guy, at the time I couldn't
pay him so I guess I repay him by giving him some realestate on my website.

* Funny
** Suicide linux
 I remember a script that would execute =rm -rf /= if you'd type a command incorrectly,
 just to teach you to be precise. 
 It was [[https://qntm.org/suicide][sucide linux]].

 I'm not running that.

* Interesting
** CGPGrey
A youtuber, although I'm linking to his [[http://www.cgpgrey.com/][website]].
He has some interesting videos (of which I know him),
but his podcasts are quite good too.

** Brady haron
Also a youtber, [[http://www.bradyharan.com/][his website]]. His numberphile channel is fun.
** How computers learn
A back to basics overview of machine learning:
https://youtu.be/T1O3ikmTEdA?t=644

Even though I knew most stuff he talked about in the beginning,
the talk later becomes more interesting since I didn't follow machine learning
that much.



** Techstratery
This guy is some kindoff analist I encountered on reddit
(probably the /r/investing sub).
He has some really interesting takes on tech companies and I learned a lot about
buisness in general from just reading his blog.
I especially liked his aggregration theory, makes me wonder if I could make one
of those.. (probably not).
https://stratechery.com/

** danluu
I found one of his articles on reddit, and he has an interesting perspective
(as moslty a hardware person).
I was reading the article [[https://danluu.com/wat/][normalization of defiance]] which talks about how
strange, shady or broken practices are born, and what one could do about them.
Then I went to the index and it turns out there is a huge treasure trove
of interesting articles on that blog.

https://danluu.com/

* Tools
** Vps comparison sites
For if you just need a cheap computing device somewhere on the internet.
I wanted one that had high CPU but didn't care about the rest, this one found
it:
http://vps-list.cryto.net/index.php?action=list
