#+TITLE: Jakartian Christmas
#+DATE: 2017-12-19 21:00
#+CATEGORY: reflection
#+Tags: work, projects, jakarta, jesiska
#+OPTIONS: toc:nil

Unfortunately Jesiska couldn't make it to Australia in time for Christmas.
Therefore I decided basically last week to go to Jakarta instead!
I personally don't care much about Christmas, but I thought the office would
be closed during this time.
(Many companies close in the Netherlands for sure during this time),
and I was just very eager to see Jesiska again.

I've been neglecting this blog a little bit lately, I've just been busy,
well actually work is a huge time sink.. it sucks.
Then I've also been trying to increase my income with various project I will
discuss next.
Although I've been neglecting the most important one which is the financial one.
It just seems so boring every time I think about it.
I need to do this soon because my bonus interest of my savings account will stop
at the new year.
This holiday conveniently overlaps with that.

The [[http://raster.click][raster]] project core is up and running. Basically anyone can sign up to it
and take advantage of it for free! Because I haven't setup payment yet!
Because many payment providers ask tax details! Which is difficult to do in
Australia!.. 
I need to go back to the Netherlands sometime to finalize this part.
Meanwhile I'm letting my father test it so I can get some feedback.
He was genuinely quite excited about the system.
This is quite a help because there are just details I don't think about,
such as making sure a week always begins on Monday (rather than it just being
whatever day your on), or making the grid clickable so it's quicker to plan in.
etc.

In the weekend I was hacking with some colleagues on a little app idea we had.
This is totally different than the raster project, and I get to work together
with some other people.
Which is nice cause most of my projects tend to be alone undertakings.
Not sure if this going to become anything, although it is ambitious,
but we're keeping it secret for now.
What we will do is try and share technical ideas and contribute to the
open source community.

I've also been considering applying for permanent residency. I looked into that
and apparently to get enough points I need to take an English test.
Seems a bit ridicules considering that I've done my masters in English,
but that's not the worst part.
The English test would cost 300$, and there is no guarantee that I get an high
enough score (although I can't imagine why I wouldn't, except for my dyslexia).

What I want most of all is too see Jesiska again.
This situation sucks even with all this stuff happening, it's pointless without
Jesiska.
