#+TITLE: Jappie lives with kangaroos
#+DATE: 2017-11-06
#+CATEGORY: reflection
#+Tags: australia, work
#+OPTIONS: toc:nil

I've been living in Australia for well over a month now and I really enjoy it!
The first two weeks were quite a wild ride, looking for my first job and finding
a permanent place to stay.

I had 3 interviews appointments prepared before arriving.
I finished them in the first week and managed to get 3 offers.
I just choice the one that looked most interesting and also happened to pay the
most!

Finding a house was a whole other level of insanity.
I think I've been in contact with a scammer, that offered an apartment in the
middle of the business district for 900$ per month (900$ per week would be more realistic).
All I had to do is deposit some money in a bank account and he would surely sent
the keys.
In another situation the rent agent wanted me to deposit money into his account
for the deposit without signing a contract! What are these people thinking?
Rental prices are trough the roof too, I'm paying 330$ per week right now..
That's about the same amount what I'd pay in the Netherlands per month!

Things seem to have settled more down now.
I have this pattern of a morning training, going to work, go to home and put
food in the microwave which I prepared over the weekend.

I quite enjoy the job too, although it's a lot less programming than what I
expected.
A lot of project management is involved too, and QA is super slow.

Meanwhile I've been working on a little side project to try and increase my
income.
It's [[http://raster.click]], a roster system aimed at restaurants.
This is basically re-doing an idea I had when I was younger, 
but this time I set it up as a service rather than selling the source.
This allows me to keep working on it if it becomes adopted by a reasonable
amount of people.

Finally I've been trying to come up with a way to invest all this money I'm
earning. The banks are much nicer in Australia because you get actual interest.
However It's too low in my opinion.
I've had several ideas ranging from making an automated trader to start mining
crypto currencies.

Sadly Jesiska hasn't arrived yet. I'm not even sure if she will before Christmas.
It seems to take ages and while I enjoy living like this,
it's not the same without Jesiska.
I actually wish I would've stayed longer in Indonesia at this point.
Oh well we'll see what happens next.
