#+Title: Major journey to Oceania
#+Date: 2017-08-07 22:00
#+Category: tools
#+Tags: webshop, money
#+PROPERTY: status draft

This is my second major journey I undertake away from my home.
First I will go for a month to indonesia, having a little holiday and meeting
my almost girlfriend. Then I will move on to australia to do a
"working holiday", where I hope to do my proffesion as a software engineer or in
AI.
In this blogpost I'll record my expectations. Because they're funny to read after
the fact.

For indonesia I'm expecting the population to be better at english then the local
chinese where in China.
This is because a chinese can say with quite some confidence he's not going to
encounter many foreigners in their life, however this may not be as true for
indonesians, especially on bali island.
My grandfather actually told me many indonesians would be capable of speaking
dutch, I seriously doubt that, and my girlfriend has confirmed this is only
true for older indonesians.
My indonesian girlfriend has also warned me life is slower in indonsia
than in China (which was already pretty laid back).

The weather will be hot in indonesia, at least in jakarta and there will be lots
of rain. I know this because we talk oftenly about the weather and I'm pretty
sure it rains there more oftenly.
Also there will be lots of trafic in jakarta, and I especially many scooters
and motorbikes. Probably similarly to the amount of Guilin.

Australia is a whole other beast of course. Everyone will speak there english
and I'll probably communicate quite easily there.
I do expect them to be incredibly polite and somewhat more laid back than dutch
people, however still 'faster life' than in China and indonesia.
By politeness I mean, trying to keep a kindoff distance from strangers and
embesolling your words so they sound 'better'.
This politenss of course breaks down between friends.

I'm expecting Sydney to be dominated by cars. Like cars to the extreme.
Whereas in the netherlands we use bycicles, you can get anywhere by car in
Sydney.
I'm expecting Sydney to be about the size of Xiamen.
Although much less dense (because of the cars needing their space).
Sydney will probably have about the same weather as the Netherlands,
laying a lot farther south than indonesia, although with the seasons mirod of
course.

So these were my expectations for these two country.
Probably full of sterio types, but this is why I do the journey.
#+BEGIN_QUOTE
Travel is fatal to prejudice, bigotry, and narrow-mindedness,
and many of our people need it sorely on these accounts.
Broad, wholesome, charitable views of men and things cannot be acquired by
vegetating in one little corner of the earth all one's lifetime.
-- Mark Twain 
#+END_QUOTE

