#+TITLE: Thesis writing tips

So I recently started writing my master thesis and looking at some of my fellow
master students their work I realized that perhaps many people have trouble with
managing references, quality control and keeping motivated.

In this post I'll explain how I managed to do it, most of these ideas are
either directly stolen from my classmates, ripped from reddit
and a few are my own "invention", but others may already have thought of it.

So perhaps the best way to see this post is as a aggragetion of techniques and
+tools+ (the tools part will be moved to another post) I used to waste less time.
So my advice to you is to skim this article and look for any ideas that seem
interesting and try them out.

* Reference management
Reference management seems to be a thing which can be quite tricky. It is
extremly tedious and dull work, and therefore I obviously don't do it by hand.
I use bibtex as core platform, I haven't compared the available options but
since it integrated with org-mode I was happy with it.

To find papers I mainly use google scholar trough the university proxy.
However sometimes papers aren't available for my university, so I'm forced to
use [[http://sci-hub.io/]] (if that link gets blocked in the future, try the
[[https://en.wikipedia.org/wiki/Sci-Hub][wikipedia entry]], wikipedia is impartial and will therefore provide a propper
link (unlike Google)).

Once I got access to the paper I will skim trough it to see if there is relevant
information.
If so I will make a copy to a paper folder and use google scholar
to generate the bibtex entry for me, there is a citation option at the bottom of
the search result, click it and then bibtex.
That little feature of Google scholar has already saved me probably several
hours of making bibtex entries.
The copied paper will have the same name as the bibtex entry key, this is
important if you want to recheck your reference later again.
Doing this will also lower the psychological barrier of re-checking
something since you won't have to go trough the entire obtain paper process
again.

Note that you shouldn't track it in your version control, because first of all
you don't expect it to change, and second of all if you push it to a public
repository you're breaking the law on a whole other level.
(distributing rather than just consuming, consuming is more easily ignored by
law enforcement).

** Books
I haven't completely solved books. It seems that getting books is a lot more
tougher than papers, probably because most scientist feel that papers should be
easy obtainable but don't necessarily feel for books the same way
(many would have written one or contributed to one).
I as a programmer feel very deeply about the necessity for freedom of
information and therefore will share some possible sources.
It will be up to the reader to decide if they should be using such sources.
However do note that these sources aren't always successful and you should
prefer obtaining papers since sci-hub works practically always.

[[http://gen.lib.rus.ec/][library genesis]] should be your first source of books, it has a crappy interface
and some mirrors may not work but if you get a result you usually also get a
book.

Then if that fails you can try and use IRC, which is described very thoroughly [[https://www.reddit.com/r/Piracy/comments/2oftbu/guide_the_idiot_proof_guide_to_downloading_ebooks/][here]].
But in short for archiving purposes, go to undernet,
join bookz (/join #bookz) and then search for your book title (@search).
Then if you get a result you need to save that file,
which isn't a book just the query result,
open that and then if it contains your book use the code to download it.

Finally there is a deseperate method I used one time.
It takes time but it can be worth the effort.
There is this concept called digital borrowing, where html drm is used to
ensure only /n/ copies get borrowed at a time.
An example of such a website is the [[https://openlibrary.org][open library]].
The system is kind off dumb since making copies of digital stuff is practically
free.
However I do like the fact that some publishers fell for it.
Anyway if it has your book you can just "borrow" it and make screenshots of each
page.
You just bypassed a bunch of html based drm and encryption with a button on your
keyboard.
Yes its pretty dumb.
(not that I disliked the openlibrary initiative or the internet archive,
in fact I love there effort of tricking the publishers. There work may save some
books from the copyright abyss, where literature gets lost forever because laws
prevent copying before the last copy gets lost).
