#+TITLE: What do you think about jakarta
#+DATE: 2017-09-28
#+CATEGORY: reflection
#+Tags: travel, indonesia, jakarta, australia
#+OPTIONS: toc:nil

Now I've finally arrived in Australia, its time to reflect upon my
expectations I had for Jakarta.
Actually.. While being in Jakarta I got asked this question quite frequently:
"What do you think about jakarta?" and I just stood there with no answer.
This post is an attempt to answer that question,
and at the same time I address the [[./journey-oceania][expectations post]] I made before.

#+BEGIN_QUOTE
For Indonesia I'm expecting the population to be better at English then the
local Chinese where in China.
#+END_QUOTE

People definitely where better at English than in China,
at least in my experience.
I had several taxi drivers that could speak some English and even the locals
know or try some words.
In China only students ever tried to speak English,
other people just didn't want to or couldn't.
I suspect this is in part due to cultural difference.
However for China the great Chinese firewall and systematic cultural isolation
(that is in part by design) helps to marginalize exposure to English for sure.

In China learning English is something which parents are willing to pay good
money for, but Indonesians are willing to go /much/ further with international
schools. All day to day conversation happens in English in these schools
and the entire education system of Singapore is blatantly copied.
This turns out in little children walking around malls speaking in an almost
perfect British accent with each other.
This was such a weird experience to hear perfect British by a 10 year old's with
Bahasa (Indonesian) all around you.

The schools are a little weird, apparently there coincide 3 different major
systems, Indonesian, Chinese and Singapore(/American).
However once I thought about this a little I realized we basically have the same
in the Netherlands, for example the 'free schools' or 'open schools'.

#+BEGIN_QUOTE
My grandfather actually told me many Indonesians would be capable of speaking
Dutch. I seriously doubt that
#+END_QUOTE

I was totally right by the way about nobody being able to speak Dutch,
I only ever met one person who said something in Dutch to me and it was done 
in a way where the words didn't make much sense.
They said 'nice to meet you' in dutch, without introducing themselves first.

#+BEGIN_QUOTE
The weather will be hot in Indonesia, at least in Jakarta and there will be lots
of rain.
#+END_QUOTE

The weather wasn't that hot actually. Most of the time I was quite comfortable
in the Jakarta heat.
There was also practically no rain, although one time there was a thunderstorm,
which killed the electricity at the place I slept.
This caused me to sleep in the heat which is a terrible experience.
After this I realized that people in the slums sleep trough this every day.
I suddenly felt very bad for those poor souls living there.
They probably never get a good night rest.

* Surprises
What really surprised me though was the food.
If you're a fan of strong flavoured foods Jakarta is a great place to go!
Another thing I didn't expect was the insane amount of malls.
They just casually build three malls next to each other, and then fill it up with
schools, fitness clubs and travel agencies, aside from the stuff you'd expect
such as shops and restaurants.
A reason for the popularity of malls may be the security that keeps out street
sellers and the AC which makes walking around there much more pleasant.

Another really nice thing was the thousand island trip.
So this is basically a boat ride of about an hour to one of the islands on the
coast of Jakarta.
However it's really similar to Aruba for about a tenth of the
cost to get there.

Okay so here we're kind off getting out of Jakarta, but what I really really
recommend is the night safari. You're being taken around the zoo in a little
train, although it goes a little to fast to experience well,
and can't take pictures for sure. However it also includes a theme park and
taking pictures with baby animals
(need to pay a little for the animals but it includes the opportunity).

What's really strange to see is that some people, have as job, guiding traffic
but they're not employed by government.
They just sort off start guiding traffic on their own and then live of the
tips.
A similar kind of people do the same for parking, they're just living parking
meters,
but they also help with getting in and out and making sure you park straight.
As a consequence all cars are parked really nicely.

Finally another peculiar thing is that there are *so* many people self employed,
it's ridiculous if you think about it.
Little shops everywhere, the traffic people, parking people etc. All self employed.
I think this is a major difference from the developed world,
where you generally start working for a boss because it just pays that much
better. But with those low wages, it's just that more attractive to start for
yourself.

* So what do I think about Jakarta?
I think that Jakarta is like an uncut gem.
It already has some really attractive attributes,
but until issues such as the crazy traffic and drinkable tap water are
addressed it isn't as good as it could be.
Still it was an amazing experience to be there and I'd definitely come back for
the food alone.
