#+TITLE: What do you think about jakarta
#+DATE: 2017-09-28
#+CATEGORY: opinion
#+Tags: travel, indonesia, jakarta, australia

Now I've finally arrived in Australia, I guess its time to reflect upon my
expectations I had for Jakarta initially.
Actually.. While being there I got asked this question,
"What do you think about jakarta?" and I just stood there, not really sure.
So lets go trough my expectations and then see how they worked out.

People definitely where better at English than in China, at least according to
my experience.
I had several taxi drivers that could speak some English and even the locals
know or try some words.
In China only students ever try to speak English,
other people just don't want to or can't.
I suspect this is in part due to cultural difference.
However for China the great Chinese firewall and systematic cultural isolation
(that is in part by design) help marginalize exposure for sure.

In China learning English is something which parents are willing to pay good
money for, but Indonesians are willing to go /much/ further with international
schools. Where all day to day conversation happens in English and the entire
education system of Singapore is blatantly copied.
This turns out in little children walking around malls speaking in an almost
perfect British accent with each other.
This was such a weird experience between all the other languages.

The schools are a little weird, apparently there coincide 3 different major
systems, Indonesian, Chinese and Singapore(/American).
However once I thought about this a little I realized we basically have the same
in the Netherlands, for example the 'free schools' or 'open schools' etc.

I was totally right by the way about nobody being able to speak dutch,
I only ever met one person who said something in Dutch to me and it was done 
in a way where the words didn't make much sense.
They said 'nice to meet you' in dutch, without introducing themselves first.

The weather wasn't that hot actually. Most of the time I was quite comfortable
in the Jakarta heat.
There was also practically no rain, although one time there was a thunderstorm,
which killed the electricity at the place I slept.
This caused me to sleep in the heat which is a terrible experience.
After this I realized that people in the slums sleep trough this every day.
I suddenly felt very bad for those poor souls living there.
They probably never get a good night rest.

What really surprised me though was the food.
If you're a fan of strong flavoured foods Jakarta is a great place to go!
Another thing I didn't expect was the insane amount of malls.
They just casually build three malls next to each other, and then fill it up with
schools, fitness clubs and travel agencies, aside from the stuff you'd expect
such as shops and restaurants.
A reason for the popularity of malls may be the security that keeps out street
sellers and the AC which makes walking around there much more pleasant.

So what do I think about Jakarta?
I think that Jakarta is like an uncut gem.
It already has some really attractive things about it,
but if until issues such as the crazy traffic and drinkable tap water are
addressed it isn't as good as it could be.
Still it was an amazing experience to be there and I'd definitely come back for
the food alone.
