#+TITLE: Work work work, ya ya ya
#+DATE: 2017-09-28
#+CATEGORY: reflection
#+Tags: travel, indonesia, jakarta, australia
#+OPTIONS: toc:nil

Last Wednesday I started my first job at [[https://www.openlearning.com/][Open Learning]]. 
It has been interesting,
I know for a fact I practically up till this point contributed almost nothing
to the company.
This is to be expected according to reddit.
I did ask a lot of questions since I was able to start programming for real
yesterday.

My first task was to basically use the platform and give feedback.
This was in hope that the UX developer could get some 'fresh' eyes on the matter.
I also was asked to measure performance and give ideas to improve that.
So I basically made a report over several hours.
I was expected to just hand that in, turns out they just wanted a meeting and
discuss my ideas.
After that little experience I changed my strategy and just made a list of
things I saw.
This was much more efficient.
I don't think they did much with the stuff I wrote down though.

Then the next task was to just follow a course and see how it works.
Specifically for this I followed the K-pop course.
Which was pretty nice to do while working I guess. 
So after finishing that I was asked to make a course and here I had so many
comments that I spent more time writing those than actually working on the
course.
Finally I setup the dev environment and that was the day.

The last day was weird, I first setup my bank account but because the bank opened
at 9:30 I came in late at around 11am.
I mean there is no real concept of 'late' at this company since they just expect
you do 8 hours per day - whenever, but it felt late.
Anyway I just spent that entire day dabbling around in react,
getting a hello world and doing some basic data flow.
