#+TITLE: Work work work, ya ya ya
#+DATE: 2017-10-02
#+CATEGORY: reflection
#+Tags: australia, work
#+OPTIONS: toc:nil

Last Wednesday I started my first job at [[https://www.openlearning.com/][Open Learning]]. 
It has been interesting,
I know for a fact I practically up till this point contributed almost nothing
to the company.
This is to be expected according to reddit.
I did ask a lot of questions since I was able to start programming for real
yesterday.

The first today I just spend on getting familiar with the platform and the last
day I dabbled around a little in react (hello world!).
The reason I for saying I did little contributions is because I just took up
more time of other employees asking questions then producing much.
Even the UX work hasn't been integrated yet because the designer was busy.

What I didn't expect however was having a good time over there.
I enjoy talking with the various people and the tasks aren't that bad.
There is also a pantry, free fruit and some tea I take advantage of.
For lunch we usually go out eating but I'm considering taking lunch as I wanna
safe some money especially this first month.

I noticed a lot of discussions where about food, actually the people at the
office seem genuinely really interested in food.
Which is good because I like trying new foods.
Unfortunately Australia doesn't seem to have much of local cuisine, but they'll
happily import dishes from neighbouring countries (which are delicious).

What's even better is that they allow you to work from home.
At this point I can't really do that yet because I'm a newby and ask a lot of
questions, but at some point I also maybe able to do that.
Once per week having no travel times would be very good!

Aside from asking to many questions (in my experience) the only other big issue
I have is leaving times.
I'm not sure how they decide upon that.
Its always kind off awkward for me to leave the place,
but on the other hand I also don't want to do (free) overwork.
I think I'm gonna ask about these things because they maybe an issue later.

The place is nice, the things they're doing could definitely help
society and I enjoy the work (not so much the UX testing part,
but it was necessary).

