#+TITLE: Portfolio
#+Tags: portfolio, work, brag
#+Category: reflection
#+Date: 2017-09-06 22:00

This page lists a lot of programming projects I made.
here my collected works I ever made.

* Solexmarkt

| Type   | Contract              |
| Status | Finished successfully |

I upgraded an existing web shop. The HTML part was already finished but it still
needed to process payments.
I added the payment system by using two external libraries.
First there was [[http://simplecartjs.org/][simplecartjs]] for offline cart configuration,
and secondly there was [[https://cakephp.org/][CakePHP]]. At the time I still used PHP a lot
(being a second year software engineering student) and had heard about [[https://nl.wikipedia.org/wiki/Model-view-controller-model][MCV]]
systems, so I decided to give CakePHP a try (which I liked a lot).
I used a MYSQL database because I was already intimately familiar with those
(and at the time it probably didn't even occurred to me to try something else).

The reason why the current website is no longer maintained by me is because
I didn't want to touch PHP anymore.
I actually wrote the original site at a loss, mainly because of my inexperience
with estimating time and poor negotiation skills.
This didn't help my motivation either.
A lot of my classmates where joking about the language at the time and
I already wrote it at a loss so I thought it best just to abandon it and focus
on my studies.

* De Huiskamer

This is my parents company. Over the years I did various automation chores
for them. Which was great because I enjoyed the work a lot but also helped out
my parents business (which usually resulted in them having more time available).
I did various projects for them.


