#+TITLE: Portfolio
#+Tags: portfolio, work, brag
#+Category: reflection

This page lists a lot of programming projects I made.
here my collected works I ever made.

* Hobby

** Dormant
These projects I want to work on later but I haven't found the time yet.

** Finished
Yes, sometime software actually gets finished.
I finished some projects.

* Proffesionally
These project I made in assignment for other people. 
Usually this means once the features are implemented and not /too/ buggy I
abondon them.
However after considerable time the employer tends to contact me again to
work on it.

** Solexmarkt
I upgraded an existing web shop. The HTML part was already finished but it still
needed to process payments.
I added the payment system by using two external libraries.
First there was [[http://simplecartjs.org/][simplecartjs]] for offline cart configuration,
and secondly there was [[https://cakephp.org/][CakePHP]]. At the time I still used PHP a lot
(being a second year software engineering student) and had heard about [[https://nl.wikipedia.org/wiki/Model-view-controller-model][MCV]]
systems, so I decided to give CakePHP a try (which I liked a lot).
I used a MYSQL database because I was already intimately familiar with those
(and at the time it probably didn't even occurred to me to try something else).

I actually wrote that site at a loss, mainly because of my inexperience
with estimating time and poor negotiation skills.

The reason why the current website is no longer maintained by me is because
I didn't want to touch PHP anymore.
A lot of my classmates where joking about the language at the time and
I already wrote it at a loss so I thought it best just to abandon it and focus
on my studies.

* Abandon ware
These projects I will never work on again.

** School projects
By definition school projects tend to become abandoned once completed.
Usually because although you may have enjoyed making it at the time,
once the grade is received you quickly abondon it.

** Hobby
Projects I once enjoyed making but now have abondoned for one or another reason.

#  LocalWords:  Solexmarkt
